### ISSUE TITLE
Failed with "The specified key does not exist" when create cos object

### ISSUE THREAD

**Issue by zyjiaobj** [ibm-cloud-docs/cloud-object-storage-cli-plugin#4]
I'm referring the document https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-cli-plugin-ic-cos-cli to upload file in to a cos bucket, but always getting a error saying that "The specified key does not exist."
```
$ ibmcloud cos put-object --bucket cos-ce-perf-bucket-dev-serving --key create_times.csv --body /Users/zyjiaobj/Code/coligo/e2e-test-agent/perf/create_times.csv
FAILED
The specified key does not exist.

$ ibmcloud cos upload --bucket cos-ce-perf-bucket-dev-serving --key create_times.csv --file /Users/zyjiaobj/Code/coligo/e2e-test-agent/perf/create_times.csv
FAILED
The specified key does not exist.
```

**Comment by cloudpitchford** [comment]
Using the path from the "body" attribute worked for me. Please let me know what you find.

**Comment by cloudpitchford** [comment]
Please feel free to open a new issue if there are more comments, questions, or concerns!
